#include "Types/Overloads.h"

namespace Soul::Types
{
	using namespace Soul::AST;

	static const std::array k_operator_overloads = {
		// Arithmetic
		// ASTNode::Operator::Add
		OperatorOverload{ .op          = ASTNode::Operator::ADD,
                         .input_types = { PrimitiveType::Kind::INT32, PrimitiveType::Kind::INT32 },
                         .return_type = PrimitiveType::Kind::INT32   },
		OperatorOverload{ .op          = ASTNode::Operator::ADD,
                         .input_types = { PrimitiveType::Kind::INT64, PrimitiveType::Kind::INT64 },
                         .return_type = PrimitiveType::Kind::INT64   },
		OperatorOverload{ .op          = ASTNode::Operator::ADD,
                         .input_types = { PrimitiveType::Kind::FLOAT32, PrimitiveType::Kind::FLOAT32 },
                         .return_type = PrimitiveType::Kind::FLOAT32 },
		OperatorOverload{ .op          = ASTNode::Operator::ADD,
                         .input_types = { PrimitiveType::Kind::FLOAT64, PrimitiveType::Kind::FLOAT64 },
                         .return_type = PrimitiveType::Kind::FLOAT64 },

		// ASTNode::Operator::Sub
		OperatorOverload{ .op          = ASTNode::Operator::SUB,
                         .input_types = { PrimitiveType::Kind::INT32, PrimitiveType::Kind::INT32 },
                         .return_type = PrimitiveType::Kind::INT32   },
		OperatorOverload{ .op          = ASTNode::Operator::SUB,
                         .input_types = { PrimitiveType::Kind::INT64, PrimitiveType::Kind::INT64 },
                         .return_type = PrimitiveType::Kind::INT64   },
		OperatorOverload{ .op          = ASTNode::Operator::SUB,
                         .input_types = { PrimitiveType::Kind::FLOAT32, PrimitiveType::Kind::FLOAT32 },
                         .return_type = PrimitiveType::Kind::FLOAT32 },
		OperatorOverload{ .op          = ASTNode::Operator::SUB,
                         .input_types = { PrimitiveType::Kind::FLOAT64, PrimitiveType::Kind::FLOAT64 },
                         .return_type = PrimitiveType::Kind::FLOAT64 },

		// ASTNode::Operator::Mul
		OperatorOverload{ .op          = ASTNode::Operator::MUL,
                         .input_types = { PrimitiveType::Kind::INT32, PrimitiveType::Kind::INT32 },
                         .return_type = PrimitiveType::Kind::INT32   },
		OperatorOverload{ .op          = ASTNode::Operator::MUL,
                         .input_types = { PrimitiveType::Kind::INT64, PrimitiveType::Kind::INT64 },
                         .return_type = PrimitiveType::Kind::INT64   },
		OperatorOverload{ .op          = ASTNode::Operator::MUL,
                         .input_types = { PrimitiveType::Kind::FLOAT32, PrimitiveType::Kind::FLOAT32 },
                         .return_type = PrimitiveType::Kind::FLOAT32 },
		OperatorOverload{ .op          = ASTNode::Operator::MUL,
                         .input_types = { PrimitiveType::Kind::FLOAT64, PrimitiveType::Kind::FLOAT64 },
                         .return_type = PrimitiveType::Kind::FLOAT64 },

		// ASTNode::Operator::Div
		OperatorOverload{ .op          = ASTNode::Operator::DIV,
                         .input_types = { PrimitiveType::Kind::INT32, PrimitiveType::Kind::INT32 },
                         .return_type = PrimitiveType::Kind::INT32   },
		OperatorOverload{ .op          = ASTNode::Operator::DIV,
                         .input_types = { PrimitiveType::Kind::INT64, PrimitiveType::Kind::INT64 },
                         .return_type = PrimitiveType::Kind::INT64   },
		OperatorOverload{ .op          = ASTNode::Operator::DIV,
                         .input_types = { PrimitiveType::Kind::FLOAT32, PrimitiveType::Kind::FLOAT32 },
                         .return_type = PrimitiveType::Kind::FLOAT32 },
		OperatorOverload{ .op          = ASTNode::Operator::DIV,
                         .input_types = { PrimitiveType::Kind::FLOAT64, PrimitiveType::Kind::FLOAT64 },
                         .return_type = PrimitiveType::Kind::FLOAT64 },

		// ASTNode::Operator::Mod
		OperatorOverload{ .op          = ASTNode::Operator::MOD,
                         .input_types = { PrimitiveType::Kind::INT32, PrimitiveType::Kind::INT32 },
                         .return_type = PrimitiveType::Kind::INT32   },
		OperatorOverload{ .op          = ASTNode::Operator::MOD,
                         .input_types = { PrimitiveType::Kind::INT64, PrimitiveType::Kind::INT64 },
                         .return_type = PrimitiveType::Kind::INT64   },

		// ASTNode::Operator::Increment
		OperatorOverload{ .op          = ASTNode::Operator::INCREMENT,
                         .input_types = { PrimitiveType::Kind::INT32 },
                         .return_type = PrimitiveType::Kind::INT32   },
		OperatorOverload{ .op          = ASTNode::Operator::INCREMENT,
                         .input_types = { PrimitiveType::Kind::INT64 },
                         .return_type = PrimitiveType::Kind::INT64   },

		// ASTNode::Operator::Decrement
		OperatorOverload{ .op          = ASTNode::Operator::DECREMENT,
                         .input_types = { PrimitiveType::Kind::INT32 },
                         .return_type = PrimitiveType::Kind::INT32   },
		OperatorOverload{ .op          = ASTNode::Operator::DECREMENT,
                         .input_types = { PrimitiveType::Kind::INT64 },
                         .return_type = PrimitiveType::Kind::INT64   },

		// ASTNode::Operator::Assign
		OperatorOverload{ .op          = ASTNode::Operator::ASSIGN,
                         .input_types = { PrimitiveType::Kind::BOOLEAN, PrimitiveType::Kind::BOOLEAN },
                         .return_type = PrimitiveType::Kind::BOOLEAN },
		OperatorOverload{ .op          = ASTNode::Operator::ASSIGN,
                         .input_types = { PrimitiveType::Kind::CHAR, PrimitiveType::Kind::CHAR },
                         .return_type = PrimitiveType::Kind::CHAR    },
		OperatorOverload{ .op          = ASTNode::Operator::ASSIGN,
                         .input_types = { PrimitiveType::Kind::FLOAT32, PrimitiveType::Kind::FLOAT32 },
                         .return_type = PrimitiveType::Kind::FLOAT32 },
		OperatorOverload{ .op          = ASTNode::Operator::ASSIGN,
                         .input_types = { PrimitiveType::Kind::FLOAT64, PrimitiveType::Kind::FLOAT64 },
                         .return_type = PrimitiveType::Kind::FLOAT64 },
		OperatorOverload{ .op          = ASTNode::Operator::ASSIGN,
                         .input_types = { PrimitiveType::Kind::INT32, PrimitiveType::Kind::INT32 },
                         .return_type = PrimitiveType::Kind::INT32   },
		OperatorOverload{ .op          = ASTNode::Operator::ASSIGN,
                         .input_types = { PrimitiveType::Kind::INT64, PrimitiveType::Kind::INT64 },
                         .return_type = PrimitiveType::Kind::INT64   },
		OperatorOverload{ .op          = ASTNode::Operator::ASSIGN,
                         .input_types = { PrimitiveType::Kind::STRING, PrimitiveType::Kind::STRING },
                         .return_type = PrimitiveType::Kind::STRING  },

		// ASTNode::Operator::AddAssign
		OperatorOverload{ .op          = ASTNode::Operator::ASSIGN_ADD,
                         .input_types = { PrimitiveType::Kind::FLOAT32, PrimitiveType::Kind::FLOAT32 },
                         .return_type = PrimitiveType::Kind::FLOAT32 },
		OperatorOverload{ .op          = ASTNode::Operator::ASSIGN_ADD,
                         .input_types = { PrimitiveType::Kind::FLOAT64, PrimitiveType::Kind::FLOAT64 },
                         .return_type = PrimitiveType::Kind::FLOAT64 },
		OperatorOverload{ .op          = ASTNode::Operator::ASSIGN_ADD,
                         .input_types = { PrimitiveType::Kind::INT32, PrimitiveType::Kind::INT32 },
                         .return_type = PrimitiveType::Kind::INT32   },
		OperatorOverload{ .op          = ASTNode::Operator::ASSIGN_ADD,
                         .input_types = { PrimitiveType::Kind::INT64, PrimitiveType::Kind::INT64 },
                         .return_type = PrimitiveType::Kind::INT64   },

		// ASTNode::Operator::SubAssign
		OperatorOverload{ .op          = ASTNode::Operator::ASSIGN_SUB,
                         .input_types = { PrimitiveType::Kind::FLOAT32, PrimitiveType::Kind::FLOAT32 },
                         .return_type = PrimitiveType::Kind::FLOAT32 },
		OperatorOverload{ .op          = ASTNode::Operator::ASSIGN_SUB,
                         .input_types = { PrimitiveType::Kind::FLOAT64, PrimitiveType::Kind::FLOAT64 },
                         .return_type = PrimitiveType::Kind::FLOAT64 },
		OperatorOverload{ .op          = ASTNode::Operator::ASSIGN_SUB,
                         .input_types = { PrimitiveType::Kind::INT32, PrimitiveType::Kind::INT32 },
                         .return_type = PrimitiveType::Kind::INT32   },
		OperatorOverload{ .op          = ASTNode::Operator::ASSIGN_SUB,
                         .input_types = { PrimitiveType::Kind::INT64, PrimitiveType::Kind::INT64 },
                         .return_type = PrimitiveType::Kind::INT64   },

		// ASTNode::Operator::MulAssign
		OperatorOverload{ .op          = ASTNode::Operator::ASSIGN_MUL,
                         .input_types = { PrimitiveType::Kind::FLOAT32, PrimitiveType::Kind::FLOAT32 },
                         .return_type = PrimitiveType::Kind::FLOAT32 },
		OperatorOverload{ .op          = ASTNode::Operator::ASSIGN_MUL,
                         .input_types = { PrimitiveType::Kind::FLOAT64, PrimitiveType::Kind::FLOAT64 },
                         .return_type = PrimitiveType::Kind::FLOAT64 },
		OperatorOverload{ .op          = ASTNode::Operator::ASSIGN_MUL,
                         .input_types = { PrimitiveType::Kind::INT32, PrimitiveType::Kind::INT32 },
                         .return_type = PrimitiveType::Kind::INT32   },
		OperatorOverload{ .op          = ASTNode::Operator::ASSIGN_MUL,
                         .input_types = { PrimitiveType::Kind::INT64, PrimitiveType::Kind::INT64 },
                         .return_type = PrimitiveType::Kind::INT64   },

		// ASTNode::Operator::DivAssign
		OperatorOverload{ .op          = ASTNode::Operator::ASSIGN_DIV,
                         .input_types = { PrimitiveType::Kind::FLOAT32, PrimitiveType::Kind::FLOAT32 },
                         .return_type = PrimitiveType::Kind::FLOAT32 },
		OperatorOverload{ .op          = ASTNode::Operator::ASSIGN_DIV,
                         .input_types = { PrimitiveType::Kind::FLOAT64, PrimitiveType::Kind::FLOAT64 },
                         .return_type = PrimitiveType::Kind::FLOAT64 },
		OperatorOverload{ .op          = ASTNode::Operator::ASSIGN_DIV,
                         .input_types = { PrimitiveType::Kind::INT32, PrimitiveType::Kind::INT32 },
                         .return_type = PrimitiveType::Kind::INT32   },
		OperatorOverload{ .op          = ASTNode::Operator::ASSIGN_DIV,
                         .input_types = { PrimitiveType::Kind::INT64, PrimitiveType::Kind::INT64 },
                         .return_type = PrimitiveType::Kind::INT64   },

		// ASTNode::Operator::ModAssign
		OperatorOverload{ .op          = ASTNode::Operator::ASSIGN_MOD,
                         .input_types = { PrimitiveType::Kind::INT32, PrimitiveType::Kind::INT32 },
                         .return_type = PrimitiveType::Kind::INT32   },
		OperatorOverload{ .op          = ASTNode::Operator::ASSIGN_MOD,
                         .input_types = { PrimitiveType::Kind::INT64, PrimitiveType::Kind::INT64 },
                         .return_type = PrimitiveType::Kind::INT64   },

		// ASTNode::Operator::Equal
		OperatorOverload{ .op          = ASTNode::Operator::EQUAL,
                         .input_types = { PrimitiveType::Kind::BOOLEAN, PrimitiveType::Kind::BOOLEAN },
                         .return_type = PrimitiveType::Kind::BOOLEAN },
		OperatorOverload{ .op          = ASTNode::Operator::EQUAL,
                         .input_types = { PrimitiveType::Kind::CHAR, PrimitiveType::Kind::CHAR },
                         .return_type = PrimitiveType::Kind::BOOLEAN },
		OperatorOverload{ .op          = ASTNode::Operator::EQUAL,
                         .input_types = { PrimitiveType::Kind::CHAR, PrimitiveType::Kind::CHAR },
                         .return_type = PrimitiveType::Kind::BOOLEAN },
		OperatorOverload{ .op          = ASTNode::Operator::EQUAL,
                         .input_types = { PrimitiveType::Kind::FLOAT32, PrimitiveType::Kind::FLOAT32 },
                         .return_type = PrimitiveType::Kind::BOOLEAN },
		OperatorOverload{ .op          = ASTNode::Operator::EQUAL,
                         .input_types = { PrimitiveType::Kind::FLOAT64, PrimitiveType::Kind::FLOAT64 },
                         .return_type = PrimitiveType::Kind::BOOLEAN },
		OperatorOverload{ .op          = ASTNode::Operator::EQUAL,
                         .input_types = { PrimitiveType::Kind::INT32, PrimitiveType::Kind::INT32 },
                         .return_type = PrimitiveType::Kind::BOOLEAN },
		OperatorOverload{ .op          = ASTNode::Operator::EQUAL,
                         .input_types = { PrimitiveType::Kind::INT64, PrimitiveType::Kind::INT64 },
                         .return_type = PrimitiveType::Kind::BOOLEAN },
		OperatorOverload{ .op          = ASTNode::Operator::EQUAL,
                         .input_types = { PrimitiveType::Kind::STRING, PrimitiveType::Kind::STRING },
                         .return_type = PrimitiveType::Kind::BOOLEAN },

		// ASTNode::Operator::NotEqual
		OperatorOverload{ .op          = ASTNode::Operator::NOT_EQUAL,
                         .input_types = { PrimitiveType::Kind::BOOLEAN, PrimitiveType::Kind::BOOLEAN },
                         .return_type = PrimitiveType::Kind::BOOLEAN },
		OperatorOverload{ .op          = ASTNode::Operator::NOT_EQUAL,
                         .input_types = { PrimitiveType::Kind::CHAR, PrimitiveType::Kind::CHAR },
                         .return_type = PrimitiveType::Kind::BOOLEAN },
		OperatorOverload{ .op          = ASTNode::Operator::NOT_EQUAL,
                         .input_types = { PrimitiveType::Kind::CHAR, PrimitiveType::Kind::CHAR },
                         .return_type = PrimitiveType::Kind::BOOLEAN },
		OperatorOverload{ .op          = ASTNode::Operator::NOT_EQUAL,
                         .input_types = { PrimitiveType::Kind::FLOAT32, PrimitiveType::Kind::FLOAT32 },
                         .return_type = PrimitiveType::Kind::BOOLEAN },
		OperatorOverload{ .op          = ASTNode::Operator::NOT_EQUAL,
                         .input_types = { PrimitiveType::Kind::FLOAT64, PrimitiveType::Kind::FLOAT64 },
                         .return_type = PrimitiveType::Kind::BOOLEAN },
		OperatorOverload{ .op          = ASTNode::Operator::NOT_EQUAL,
                         .input_types = { PrimitiveType::Kind::INT32, PrimitiveType::Kind::INT32 },
                         .return_type = PrimitiveType::Kind::BOOLEAN },
		OperatorOverload{ .op          = ASTNode::Operator::NOT_EQUAL,
                         .input_types = { PrimitiveType::Kind::INT64, PrimitiveType::Kind::INT64 },
                         .return_type = PrimitiveType::Kind::BOOLEAN },
		OperatorOverload{ .op          = ASTNode::Operator::NOT_EQUAL,
                         .input_types = { PrimitiveType::Kind::STRING, PrimitiveType::Kind::STRING },
                         .return_type = PrimitiveType::Kind::BOOLEAN },

		// ASTNode::Operator::Greater
		OperatorOverload{ .op          = ASTNode::Operator::GREATER,
                         .input_types = { PrimitiveType::Kind::BOOLEAN, PrimitiveType::Kind::BOOLEAN },
                         .return_type = PrimitiveType::Kind::BOOLEAN },
		OperatorOverload{ .op          = ASTNode::Operator::GREATER,
                         .input_types = { PrimitiveType::Kind::CHAR, PrimitiveType::Kind::CHAR },
                         .return_type = PrimitiveType::Kind::BOOLEAN },
		OperatorOverload{ .op          = ASTNode::Operator::GREATER,
                         .input_types = { PrimitiveType::Kind::FLOAT32, PrimitiveType::Kind::FLOAT32 },
                         .return_type = PrimitiveType::Kind::BOOLEAN },
		OperatorOverload{ .op          = ASTNode::Operator::GREATER,
                         .input_types = { PrimitiveType::Kind::FLOAT64, PrimitiveType::Kind::FLOAT64 },
                         .return_type = PrimitiveType::Kind::BOOLEAN },
		OperatorOverload{ .op          = ASTNode::Operator::GREATER,
                         .input_types = { PrimitiveType::Kind::INT32, PrimitiveType::Kind::INT32 },
                         .return_type = PrimitiveType::Kind::BOOLEAN },
		OperatorOverload{ .op          = ASTNode::Operator::GREATER,
                         .input_types = { PrimitiveType::Kind::INT64, PrimitiveType::Kind::INT64 },
                         .return_type = PrimitiveType::Kind::BOOLEAN },

		// ASTNode::Operator::GreaterEqual
		OperatorOverload{ .op          = ASTNode::Operator::GREATER_EQUAL,
                         .input_types = { PrimitiveType::Kind::BOOLEAN, PrimitiveType::Kind::BOOLEAN },
                         .return_type = PrimitiveType::Kind::BOOLEAN },
		OperatorOverload{ .op          = ASTNode::Operator::GREATER_EQUAL,
                         .input_types = { PrimitiveType::Kind::CHAR, PrimitiveType::Kind::CHAR },
                         .return_type = PrimitiveType::Kind::BOOLEAN },
		OperatorOverload{ .op          = ASTNode::Operator::GREATER_EQUAL,
                         .input_types = { PrimitiveType::Kind::FLOAT32, PrimitiveType::Kind::FLOAT32 },
                         .return_type = PrimitiveType::Kind::BOOLEAN },
		OperatorOverload{ .op          = ASTNode::Operator::GREATER_EQUAL,
                         .input_types = { PrimitiveType::Kind::FLOAT64, PrimitiveType::Kind::FLOAT64 },
                         .return_type = PrimitiveType::Kind::BOOLEAN },
		OperatorOverload{ .op          = ASTNode::Operator::GREATER_EQUAL,
                         .input_types = { PrimitiveType::Kind::INT32, PrimitiveType::Kind::INT32 },
                         .return_type = PrimitiveType::Kind::BOOLEAN },
		OperatorOverload{ .op          = ASTNode::Operator::GREATER_EQUAL,
                         .input_types = { PrimitiveType::Kind::INT64, PrimitiveType::Kind::INT64 },
                         .return_type = PrimitiveType::Kind::BOOLEAN },

		// ASTNode::Operator::Less
		OperatorOverload{ .op          = ASTNode::Operator::LESS,
                         .input_types = { PrimitiveType::Kind::BOOLEAN, PrimitiveType::Kind::BOOLEAN },
                         .return_type = PrimitiveType::Kind::BOOLEAN },
		OperatorOverload{ .op          = ASTNode::Operator::LESS,
                         .input_types = { PrimitiveType::Kind::CHAR, PrimitiveType::Kind::CHAR },
                         .return_type = PrimitiveType::Kind::BOOLEAN },
		OperatorOverload{ .op          = ASTNode::Operator::LESS,
                         .input_types = { PrimitiveType::Kind::FLOAT32, PrimitiveType::Kind::FLOAT32 },
                         .return_type = PrimitiveType::Kind::BOOLEAN },
		OperatorOverload{ .op          = ASTNode::Operator::LESS,
                         .input_types = { PrimitiveType::Kind::FLOAT64, PrimitiveType::Kind::FLOAT64 },
                         .return_type = PrimitiveType::Kind::BOOLEAN },
		OperatorOverload{ .op          = ASTNode::Operator::LESS,
                         .input_types = { PrimitiveType::Kind::INT32, PrimitiveType::Kind::INT32 },
                         .return_type = PrimitiveType::Kind::BOOLEAN },
		OperatorOverload{ .op          = ASTNode::Operator::LESS,
                         .input_types = { PrimitiveType::Kind::INT64, PrimitiveType::Kind::INT64 },
                         .return_type = PrimitiveType::Kind::BOOLEAN },

		// ASTNode::Operator::LessEqual
		OperatorOverload{ .op          = ASTNode::Operator::LESS_EQUAL,
                         .input_types = { PrimitiveType::Kind::BOOLEAN, PrimitiveType::Kind::BOOLEAN },
                         .return_type = PrimitiveType::Kind::BOOLEAN },
		OperatorOverload{ .op          = ASTNode::Operator::LESS_EQUAL,
                         .input_types = { PrimitiveType::Kind::CHAR, PrimitiveType::Kind::CHAR },
                         .return_type = PrimitiveType::Kind::BOOLEAN },
		OperatorOverload{ .op          = ASTNode::Operator::LESS_EQUAL,
                         .input_types = { PrimitiveType::Kind::FLOAT32, PrimitiveType::Kind::FLOAT32 },
                         .return_type = PrimitiveType::Kind::BOOLEAN },
		OperatorOverload{ .op          = ASTNode::Operator::LESS_EQUAL,
                         .input_types = { PrimitiveType::Kind::FLOAT64, PrimitiveType::Kind::FLOAT64 },
                         .return_type = PrimitiveType::Kind::BOOLEAN },
		OperatorOverload{ .op          = ASTNode::Operator::LESS_EQUAL,
                         .input_types = { PrimitiveType::Kind::INT32, PrimitiveType::Kind::INT32 },
                         .return_type = PrimitiveType::Kind::BOOLEAN },
		OperatorOverload{ .op          = ASTNode::Operator::LESS_EQUAL,
                         .input_types = { PrimitiveType::Kind::INT64, PrimitiveType::Kind::INT64 },
                         .return_type = PrimitiveType::Kind::BOOLEAN },

		// Logical
		OperatorOverload{ .op          = ASTNode::Operator::LOGICAL_NOT,
                         .input_types = { PrimitiveType::Kind::BOOLEAN },
                         .return_type = PrimitiveType::Kind::BOOLEAN },
		OperatorOverload{ .op          = ASTNode::Operator::LOGICAL_AND,
                         .input_types = { PrimitiveType::Kind::BOOLEAN, PrimitiveType::Kind::BOOLEAN },
                         .return_type = PrimitiveType::Kind::BOOLEAN },
		OperatorOverload{ .op          = ASTNode::Operator::LOGICAL_OR,
                         .input_types = { PrimitiveType::Kind::BOOLEAN, PrimitiveType::Kind::BOOLEAN },
                         .return_type = PrimitiveType::Kind::BOOLEAN },
	};

	std::span<const OperatorOverload> OperatorOverload::All() noexcept { return k_operator_overloads; }
}  // namespace Soul::Types
