#pragma once

#include "Common/SourceOffset.h"
#include "Core/StringView.h"
#include "Soul.h"

namespace Soul::Lexer
{
	enum class TokenType : UInt8
	{
		TOKEN_KEYWORD_BREAK,
		TOKEN_KEYWORD_CAST,
		TOKEN_KEYWORD_CONTINUE,
		TOKEN_KEYWORD_ELSE,
		TOKEN_KEYWORD_FALSE,
		TOKEN_KEYWORD_FN,
		TOKEN_KEYWORD_FOR,
		TOKEN_KEYWORD_IF,
		TOKEN_KEYWORD_LET,
		TOKEN_KEYWORD_MUT,
		TOKEN_KEYWORD_NATIVE,
		TOKEN_KEYWORD_NULL,
		TOKEN_KEYWORD_RETURN,
		TOKEN_KEYWORD_STRUCT,
		TOKEN_KEYWORD_TRUE,
		TOKEN_KEYWORD_WHILE,

		TOKEN_LITERAL_FLOAT,
		TOKEN_LITERAL_IDENTIFIER,
		TOKEN_LITERAL_INTEGER,
		TOKEN_LITERAL_STRING,

		TOKEN_SYMBOL_AMPERSAND,
		TOKEN_SYMBOL_AMPERSAND_AMPERSAND,
		TOKEN_SYMBOL_BANG,
		TOKEN_SYMBOL_BANG_EQUAL,
		TOKEN_SYMBOL_BRACE_LEFT,
		TOKEN_SYMBOL_BRACE_RIGHT,
		TOKEN_SYMBOL_BRACKET_LEFT,
		TOKEN_SYMBOL_BRACKET_RIGHT,
		TOKEN_SYMBOL_CARET,
		TOKEN_SYMBOL_COLON,
		TOKEN_SYMBOL_COLON_COLON,
		TOKEN_SYMBOL_COMMA,
		TOKEN_SYMBOL_DOT,
		TOKEN_SYMBOL_EQUAL,
		TOKEN_SYMBOL_EQUAL_EQUAL,
		TOKEN_SYMBOL_GREATER,
		TOKEN_SYMBOL_GREATER_EQUAL,
		TOKEN_SYMBOL_LESS,
		TOKEN_SYMBOL_LESS_EQUAL,
		TOKEN_SYMBOL_MINUS,
		TOKEN_SYMBOL_MINUS_EQUAL,
		TOKEN_SYMBOL_MINUS_MINUS,
		TOKEN_SYMBOL_PERCENT,
		TOKEN_SYMBOL_PERCENT_EQUAL,
		TOKEN_SYMBOL_PAREN_LEFT,
		TOKEN_SYMBOL_PAREN_RIGHT,
		TOKEN_SYMBOL_PIPE,
		TOKEN_SYMBOL_PIPE_PIPE,
		TOKEN_SYMBOL_PLUS,
		TOKEN_SYMBOL_PLUS_EQUAL,
		TOKEN_SYMBOL_PLUS_PLUS,
		TOKEN_SYMBOL_QUESTION_MARK,
		TOKEN_SYMBOL_SEMICOLON,
		TOKEN_SYMBOL_SLASH,
		TOKEN_SYMBOL_SLASH_EQUAL,
		TOKEN_SYMBOL_STAR,
		TOKEN_SYMBOL_STAR_EQUAL,

		TOKEN_SPECIAL_ERROR,
		TOKEN_SPECIAL_END_OF_FILE,
	};

	/**
	 * @brief Represents a single lexical token, otherwise known as Lexeme.
	 */
	struct Token
	{
		SourceOffset offset;
		TokenType type;

		static Bool8 Equals(Token lhs, Token rhs) noexcept;
		static StringView Name(TokenType type) noexcept;
		static StringView NameInternal(TokenType type) noexcept;
	};
}  // namespace Soul::Lexer
