OPCODE(OP_NOOP)

// Register load value
OPCODE(OP_LOADI) OPCODE(OP_LOADF)

// Control flow
OPCODE(OP_JMP) OPCODE(OP_JMP_LONG) // Unconditional jumps

// Arythmetic opcodes
OPCODE(OP_ADDI) OPCODE(OP_ADDF)
OPCODE(OP_SUBI) OPCODE(OP_SUBF)
OPCODE(OP_MULI) OPCODE(OP_MULF)
OPCODE(OP_DIVI) OPCODE(OP_DIVF)

OPCODE(OP_RETURN)
OPCODE(OP_HALT)

OPCODE(OPCODE_COUNT)

#undef OPCODE
