OPCODE(OP_NOOP)

// Stack operations
OPCODE(OP_PUSH_CONST)
OPCODE(OP_POP)

// Control flow
OPCODE(OP_JMP) OPCODE(OP_JMP_LONG) // Unconditional jumps

// Arythmetic opcodes
OPCODE(OP_ADDI) OPCODE(OP_SUBI) OPCODE(OP_MULI) OPCODE(OP_DIVI)
OPCODE(OP_ADDF) OPCODE(OP_SUBF) OPCODE(OP_MULF) OPCODE(OP_DIVF)

OPCODE(OP_RETURN)
OPCODE(OP_HALT)

// @Temp
OPCODE(OP_PRINT)

OPCODE(OPCODE_COUNT)

#undef OPCODE
